### ISSUE TITLE
Sözlük

### ISSUE THREAD

**Issue by yesnt01** [isik-kaplan/eksiclone#15]
Usta centos sunucum var cpanel kurulu, bunu siteme nasıl kurabilrim yardımcı olursan çok sevinirim, denedim başaramadım.

**Comment by ozkansen** [comment]
Kurulumda ne gibi bir hata aldın ayrıntı verebilirsen yardımcı olmaya çalışalım.

**Comment by yesnt01** [comment]
Dürüst olmak gerekirse pyhton çok yabancı geldi, php scriptlerle çalışıyordum şu ana kadar ama bu scripte o kadar çok ihtiyacım var ki, proje için domaini aldım

**Comment by yesnt01** [comment]
`  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/eksiclone/eksiclone/eksiclone/urls.py", line 19, in <module>
    from mainsite.urls import mainsite_urls
  File "/root/eksiclone/eksiclone/mainsite/urls.py", line 3, in <module>
    from django_urls import UrlManager
ModuleNotFoundError: No module named 'django_urls'
`

**Comment by yesnt01** [comment]
3 adet sunucuda ikisi linux 1 i windows olmak üzere denedim ama hep farklı hatalarla karşılaştım :/

**Comment by ozkansen** [comment]
django-urls kütüphanesi kurulu değil, `recommends.txt` içerisine django-urls ekleyip tekrar deneyebilirmisin.

**Comment by yesnt01** [comment]
ozkan hocam o sorunları geçtim ancak ne yaptıysam hep başka hatalar aldım. Kurulumu bilmediğimden ve bu dil çok yabancı geldiğinden bazı noktaları istemsizce atlıyor olabilirim bunu da göz ardı etmek istemiyorum. sizce windows makinede mi linux makinede mi denemeliyim. bir kere daha deneyeceğim, pes etmek istemiyorum

**Comment by ozkansen** [comment]
Linux makinede denemenizi tavsiye ederim, windows da derleme gerektiren sorunlarla uğraşabilirsiniz.
`psycopg2` paketi için `libpq5-dev`, `python3-dev` ve `build-essential` paketinin yüklü olması, enviorement bilgileri tanımlı değilse `settings.py` dosyasında database bilgilerini elle düzeltmeniz gerekiyor, bunlardan başka sorun olmaması lazım.

**Comment by yesnt01** [comment]
özkan hocam size nasıl ulaşabilirim

**Comment by ozkansen** [comment]
Hocam buradan yardımcı olayım, başka arkadaşlara da faydalı olur.
Şurada örnek bir kurulum yaptım buraya kadarını biliyorum gerisi için @isik-kaplan hocam yardımcı olur.

[![asciicast](https://asciinema.org/a/336611.svg)](https://asciinema.org/a/336611)

**Comment by isik-kaplan** [comment]
Merhaba, bu proje ~2016'dan kalma benim django öğrenme projemdi, üzerine 5-10 commit çok kötü yerlerini düzeltmiştim geçen sene ve paylaşmıştım. Ama production-ready olmaktan uzak; sadece core yapıların ve veri modellerinin olduğu bir proje şuanda. Yine de bariz hatalar varsa hatanın ne olduğunu yazarak issua açarsanız yardımcı olmaya çalışabilirim, ama production-ready hale getirebilecek kadar zamanım malesef yok. 

@ozkansen sqlite3 ile kurmuş ve göstermiş(teşekkürler), adımları takip ederseniz sorun çıkacağını düşünmüyorum kurulum ile ilgili.
